# Generated by Django 4.2.11 on 2024-03-28 07:54

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_prj', '0002_alter_task_options_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to='images/thumbnails/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('png', 'jpg', 'webp', 'jpeg', 'gif'))], verbose_name='Превью поста'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders_task', to='project_prj.task', verbose_name='Услуга'),
        ),
    ]
